// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjFo8UlJ_4EXTzvl8-yy_bywrW91CMW-g',
    appId: '1:951261389645:web:ec33dddf36f57a99368d04',
    messagingSenderId: '951261389645',
    projectId: 'smallblog-31395',
    authDomain: 'smallblog-31395.firebaseapp.com',
    storageBucket: 'smallblog-31395.appspot.com',
    measurementId: 'G-R49JLTGYLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwoA1DUa4vwmZPmwqhVpKyQHQmhyh6Ero',
    appId: '1:951261389645:android:c3efd6f4c2d8350b368d04',
    messagingSenderId: '951261389645',
    projectId: 'smallblog-31395',
    storageBucket: 'smallblog-31395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsbaTr-ikH3yJ2XkPncyhCZ9TKgBhqGw',
    appId: '1:951261389645:ios:bc53dde041806667368d04',
    messagingSenderId: '951261389645',
    projectId: 'smallblog-31395',
    storageBucket: 'smallblog-31395.appspot.com',
    iosClientId: '951261389645-lbmu526cte4a9hpbplqt93ju5k0lvflq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smallBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsbaTr-ikH3yJ2XkPncyhCZ9TKgBhqGw',
    appId: '1:951261389645:ios:bc53dde041806667368d04',
    messagingSenderId: '951261389645',
    projectId: 'smallblog-31395',
    storageBucket: 'smallblog-31395.appspot.com',
    iosClientId: '951261389645-lbmu526cte4a9hpbplqt93ju5k0lvflq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smallBlog',
  );
}
